update divvy_stations set id = '91' where name = 'Clinton St & Washington Blvd';
update divvy_stations set id = '85' where name = 'Michigan Ave & Oak St';
update divvy_stations set id = '88' where name = 'May St & Randolph St';
update divvy_stations set id = '17' where name = 'Wood St & Division St';
update divvy_stations set id = '28' where name = 'Larrabee St & Menomonee St';
update divvy_stations set id = '45' where name = 'Michigan Ave & Congress Pkwy';
update divvy_stations set id = '61' where name = 'Wood St & Milwaukee Ave';
update divvy_stations set id = '32' where name = 'Racine Ave & Congress Pkwy';
update divvy_stations set id = '68' where name = 'Clinton St & Tilden St';
update divvy_stations set id = '19' where name = 'Loomis St & Taylor St';
update divvy_stations set id = '34' where name = 'Cannon Dr & Fullerton Ave';
update divvy_stations set id = '349' where name = 'Halsted St & Wrightwood Ave';
update divvy_stations set id = '320' where name = 'Loomis St & Lexington St';
update divvy_stations set id = '55' where name = 'Halsted St & James M Rochford St';
update divvy_stations set id = '42' where name = 'Wabash Ave & Cermak Rd';
update divvy_stations set id = '36' where name = 'Franklin St & Jackson Blvd';
update divvy_stations set id = '81' where name = 'Daley Center Plaza';
update divvy_stations set id = '340' where name = 'Clark St & Wrightwood Ave';
update divvy_stations set id = '37' where name = 'Dearborn St & Adams St';
update divvy_stations set id = '44' where name = 'State St & Randolph St';
update divvy_stations set id = '94' where name = 'Lincoln Ave & Armitage Ave';
update divvy_stations set id = '76' where name = 'Lake Shore Dr & Monroe St';
update divvy_stations set id = '90' where name = 'Millennium Park';
update divvy_stations set id = '52' where name = 'Michigan Ave & Lake St';
update divvy_stations set id = '51' where name = 'Clark St & Randolph St';
update divvy_stations set id = '190' where name = 'Southport Ave & Wrightwood Ave';
update divvy_stations set id = '24' where name = 'Fairbanks Ct & Grand Ave';
update divvy_stations set id = '54' where name = 'Ogden Ave & Chicago Ave';
update divvy_stations set id = '20' where name = 'Sheffield Ave & Kingsbury St';
update divvy_stations set id = '31' where name = 'Franklin St & Chicago Ave';
update divvy_stations set id = '74' where name = 'Kingsbury St & Erie St';
update divvy_stations set id = '77' where name = 'Clinton St & Madison St';
update divvy_stations set id = '69' where name = 'Damen Ave & Pierce Ave';
update divvy_stations set id = '60' where name = 'Dayton St & North Ave';
update divvy_stations set id = '59' where name = 'Wabash Ave & Roosevelt Rd';
update divvy_stations set id = '67' where name = 'Sheffield Ave & Fullerton Ave';
update divvy_stations set id = '73' where name = 'Jefferson St & Monroe St';
update divvy_stations set id = '29' where name = 'Noble St & Milwaukee Ave';
update divvy_stations set id = '311' where name = 'Lincoln Ave & Eastwood Ave';
update divvy_stations set id = '72' where name = 'State St & 16th St';
update divvy_stations set id = '75' where name = 'Canal St & Jackson Blvd';
update divvy_stations set id = '48' where name = 'Larrabee St & Kingsbury St';
update divvy_stations set id = '16' where name = 'Wood St & North Ave';
update divvy_stations set id = '108' where name = 'Halsted St & Polk St';
update divvy_stations set id = '5' where name = 'State St & Harrison St';
update divvy_stations set id = '30' where name = 'Ashland Ave & Augusta Blvd';
update divvy_stations set id = '26' where name = 'McClurg Ct & Illinois St';
update divvy_stations set id = '25' where name = 'Michigan Ave & Pearson St';
update divvy_stations set id = '15' where name = 'Racine Ave & 18th St';
update divvy_stations set id = '66' where name = 'Clinton St & Lake St';
update divvy_stations set id = '166' where name = 'Ashland Ave & Wrightwood Ave';
update divvy_stations set id = '21' where name = 'Aberdeen St & Jackson Blvd';
update divvy_stations set id = '58' where name = 'Ashland Ave & Armitage Ave';
update divvy_stations set id = '350' where name = 'Ashland Ave & Chicago Ave';
update divvy_stations set id = '22' where name = 'May St & Taylor St';
update divvy_stations set id = '251' where name = 'Clarendon Ave & Leland Ave';
update divvy_stations set id = '46' where name = 'Wells St & Walton St';
update divvy_stations set id = '27' where name = 'Larrabee St & North Ave';
update divvy_stations set id = '341' where name = 'Adler Planetarium';
update divvy_stations set id = '149' where name = 'Calumet Ave & 33rd St';
update divvy_stations set id = '127' where name = 'Lincoln Ave & Fullerton Ave';
update divvy_stations set id = '164' where name = 'Franklin St & Lake St';
update divvy_stations set id = '279' where name = 'Halsted St & 35th St';
update divvy_stations set id = '252' where name = 'Greenwood Ave & 47th St';
update divvy_stations set id = '232' where name = 'Pine Grove Ave & Addison St';
update divvy_stations set id = '351' where name = 'Cottage Grove Ave & 51st St';
update divvy_stations set id = '62' where name = 'McCormick Place';
update divvy_stations set id = '99' where name = 'Lake Shore Dr & Ohio St';
update divvy_stations set id = '84' where name = 'Green St & Milwaukee Ave';
update divvy_stations set id = '56' where name = 'Desplaines St & Kinzie St';
update divvy_stations set id = '50' where name = 'Clark St & Congress Pkwy';
update divvy_stations set id = '250' where name = 'Ashland Ave & Wellington Ave';
update divvy_stations set id = '262' where name = 'Halsted St & 37th St';
update divvy_stations set id = '97' where name = 'Museum Campus';
update divvy_stations set id = '57' where name = 'Clinton St & Roosevelt Rd';
update divvy_stations set id = '43' where name = 'Michigan Ave & Washington St';
update divvy_stations set id = '33' where name = 'State St & Van Buren St';
update divvy_stations set id = '47' where name = 'State St & Kinzie St';
update divvy_stations set id = '322' where name = 'Kimbark Ave & 53rd St';
update divvy_stations set id = '14' where name = 'Morgan St & 18th St';
update divvy_stations set id = '87' where name = 'Racine Ave & Fullerton Ave';
update divvy_stations set id = '300' where name = 'Broadway & Barry Ave';
update divvy_stations set id = '71' where name = 'Morgan St & Lake St';
update divvy_stations set id = '255' where name = 'Indiana Ave & Roosevelt Rd';
update divvy_stations set id = '23' where name = 'Orleans St & Elm St';
update divvy_stations set id = '249' where name = 'Montrose Harbor';
update divvy_stations set id = '244' where name = 'Ravenswood Ave & Irving Park Rd';
update divvy_stations set id = '93' where name = 'Sheffield Ave & Willow St';
update divvy_stations set id = '49' where name = 'Dearborn St & Monroe St';
update divvy_stations set id = '53' where name = 'Wells St & Erie St';
update divvy_stations set id = '80' where name = 'Aberdeen St & Madison St';
update divvy_stations set id = '121' where name = 'Blackstone Ave & Hyde Park Blvd';
update divvy_stations set id = '220' where name = 'Hampden Ct & Diversey Pkwy';
update divvy_stations set id = '13' where name = 'Wilton Ave & Diversey Pkwy';
update divvy_stations set id = '181' where name = 'LaSalle St & Illinois St';
update divvy_stations set id = '92' where name = 'Carpenter St & Huron St';
update divvy_stations set id = '86' where name = 'Eckhart Park';
update divvy_stations set id = '285' where name = 'Wood St & Grand Ave';
update divvy_stations set id = '348' where name = 'California Ave & 21st St';
update divvy_stations set id = '312' where name = 'Clarendon Ave & Gordon Ter';
update divvy_stations set id = '112' where name = 'Green St & Randolph St';
update divvy_stations set id = '179' where name = 'Martin Luther King Dr & Oakwood Blvd';
update divvy_stations set id = '165' where name = 'Clark St & Waveland Ave';
update divvy_stations set id = '328' where name = 'Ellis Ave & 58th St';
update divvy_stations set id = '305' where name = 'Western Ave & Division St';
update divvy_stations set id = '319' where name = 'Greenview Ave & Diversey Pkwy';
update divvy_stations set id = '313' where name = 'Lakeview Ave & Fullerton Pkwy';
update divvy_stations set id = '195' where name = 'Columbus Dr & Randolph St';
update divvy_stations set id = '141' where name = 'Clark St & Lincoln Ave';
update divvy_stations set id = '330' where name = 'Lincoln Ave & Addison St';
update divvy_stations set id = '192' where name = 'Canal St & Adams St';
update divvy_stations set id = '188' where name = 'Greenview Ave & Fullerton Ave';
update divvy_stations set id = '98' where name = 'LaSalle St & Washington St';
update divvy_stations set id = '169' where name = 'Canal St & Harrison St';
update divvy_stations set id = '273' where name = 'Michigan Ave & 18th St';
update divvy_stations set id = '123' where name = 'California Ave & Milwaukee Ave';
update divvy_stations set id = '159' where name = 'Claremont Ave & Hirsch St';
update divvy_stations set id = '100' where name = 'Orleans St & Merchandise Mart Plaza';
update divvy_stations set id = '178' where name = 'State St & 19th St';
update divvy_stations set id = '115' where name = 'Sheffield Ave & Wellington Ave';
update divvy_stations set id = '170' where name = 'Clinton St & 18th St';
update divvy_stations set id = '134' where name = 'Peoria St & Jackson Blvd';
update divvy_stations set id = '150' where name = 'Fort Dearborn Dr & 31st St';
update divvy_stations set id = '135' where name = 'Halsted St & 21st St';
update divvy_stations set id = '167' where name = 'Damen Ave & Coulter St';
update divvy_stations set id = '147' where name = 'Indiana Ave & 26th St';
update divvy_stations set id = '129' where name = 'Blue Island Ave & 18th St';
update divvy_stations set id = '183' where name = 'Damen Ave & Augusta Blvd';
update divvy_stations set id = '153' where name = 'Southport Ave & Wellington Ave';
update divvy_stations set id = '162' where name = 'Damen Ave & Wellington Ave';
update divvy_stations set id = '116' where name = 'Western Ave & Winnebago Ave';
update divvy_stations set id = '171' where name = 'May St & Cullerton St';
update divvy_stations set id = '130' where name = 'Damen Ave & Division St';
update divvy_stations set id = '185' where name = 'Stave St & Armitage Ave';
update divvy_stations set id = '174' where name = 'Canal St & Madison St';
update divvy_stations set id = '160' where name = 'Campbell Ave & North Ave';
update divvy_stations set id = '158' where name = 'Milwaukee Ave & Wabansia Ave';
update divvy_stations set id = '186' where name = 'Ogden Ave & Race Ave';
update divvy_stations set id = '146' where name = 'Loomis St & Jackson Blvd';
update divvy_stations set id = '119' where name = 'Ashland Ave & Lake St';
update divvy_stations set id = '321' where name = 'Wabash Ave & 8th St';
update divvy_stations set id = '122' where name = 'Ogden Ave & Congress Pkwy';
update divvy_stations set id = '126' where name = 'Clark St & North Ave';
update divvy_stations set id = '163' where name = 'Paulina St & Diversey Pkwy';
update divvy_stations set id = '154' where name = 'Southport Ave & Belmont Ave';
update divvy_stations set id = '212' where name = 'Wells St & Ohio St';
update divvy_stations set id = '152' where name = 'Lincoln Ave & Diversey Pkwy';
update divvy_stations set id = '347' where name = 'Ashland Ave & Grace St';
update divvy_stations set id = '137' where name = 'Morgan Ave & 14th Pl';
update divvy_stations set id = '136' where name = 'Racine Ave & 13th St';
update divvy_stations set id = '173' where name = 'Mies van der Rohe Way & Chicago Ave';
update divvy_stations set id = '176' where name = 'Clark St & Elm St';
update divvy_stations set id = '118' where name = 'Sedgwick St & North Ave';
update divvy_stations set id = '224' where name = 'Halsted St & Willow St';
update divvy_stations set id = '110' where name = 'State St & Erie St';
update divvy_stations set id = '140' where name = 'Dearborn Pkwy & Delaware Pl';
update divvy_stations set id = '106' where name = 'State St & Pearson St';
update divvy_stations set id = '157' where name = 'Lake Shore Dr & Wellington Ave';
update divvy_stations set id = '111' where name = 'Sedgwick St & Huron St';
update divvy_stations set id = '114' where name = 'Sheffield Ave & Addison St';
update divvy_stations set id = '117' where name = 'Wilton Ave & Belmont Ave';
update divvy_stations set id = '233' where name = 'Sangamon St & Washington Blvd';
update divvy_stations set id = '144' where name = 'Larrabee St & Webster Ave';
update divvy_stations set id = '229' where name = 'Southport Ave & Roscoe St';
update divvy_stations set id = '156' where name = 'Clark St & Wellington Ave';
update divvy_stations set id = '143' where name = 'Sedgwick St & Webster Ave';
update divvy_stations set id = '168' where name = 'Michigan Ave & 14th St';
update divvy_stations set id = '175' where name = 'Wells St & Polk St';
update divvy_stations set id = '128' where name = 'Damen Ave & Chicago Ave';
update divvy_stations set id = '314' where name = 'Ravenswood Ave & Berteau Ave';
update divvy_stations set id = '124' where name = 'Damen Ave & Cullerton St';
update divvy_stations set id = '35' where name = 'Streeter Dr & Illinois St';
update divvy_stations set id = '138' where name = 'Clybourn Ave & Division St';
update divvy_stations set id = '184' where name = 'State St & 35th St';
update divvy_stations set id = '109' where name = '900 W Harrison';
update divvy_stations set id = '120' where name = 'Wentworth Ave & Archer Ave';
update divvy_stations set id = '191' where name = 'Canal St & Monroe St';
update divvy_stations set id = '196' where name = 'Cityfront Plaza & N Water St';
update divvy_stations set id = '194' where name = 'State St & Wacker Dr';
update divvy_stations set id = '199' where name = 'Wabash Ave & Grand Ave';
update divvy_stations set id = '197' where name = 'Michigan Ave & Madison St';
update divvy_stations set id = '198' where name = 'Halsted St & Madison St';
update divvy_stations set id = '240' where name = 'Sheridan Rd & Irving Park Rd';
update divvy_stations set id = '202' where name = 'Halsted St & 18th St';
update divvy_stations set id = '177' where name = 'Theater on the Lake';
update divvy_stations set id = '200' where name = 'King Dr & 47th St';
update divvy_stations set id = '205' where name = 'Paulina St & 18th St';
update divvy_stations set id = '206' where name = 'Halsted St & Archer Ave';
update divvy_stations set id = '204' where name = 'Prairie Ave & Garfield Blvd';
update divvy_stations set id = '211' where name = 'St Clair St & Erie St';
update divvy_stations set id = '215' where name = 'Damen Ave & Madison St';
update divvy_stations set id = '207' where name = 'Emerald Ave & 28th St';
update divvy_stations set id = '201' where name = 'Indiana Ave & 40th St';
update divvy_stations set id = '203' where name = 'Western Ave & 21st St';
update divvy_stations set id = '210' where name = 'Ashland Ave & Division St';
update divvy_stations set id = '217' where name = 'May St & Fulton St';
update divvy_stations set id = '209' where name = 'Normal Ave & Archer Ave';
update divvy_stations set id = '214' where name = 'Damen Ave & Grand Ave';
update divvy_stations set id = '216' where name = 'California Ave & Division St';
update divvy_stations set id = '213' where name = 'Leavitt St & North Ave';
update divvy_stations set id = '208' where name = 'Ashland Ave & 21st St';
update divvy_stations set id = '225' where name = 'Halsted St & Dickens Ave';
update divvy_stations set id = '226' where name = 'Racine Ave & Belmont Ave';
update divvy_stations set id = '227' where name = 'Southport Ave & Waveland Ave';
update divvy_stations set id = '219' where name = 'Damen Ave & Cortland St';
update divvy_stations set id = '230' where name = 'Lincoln Ave & Roscoe St';
update divvy_stations set id = '231' where name = 'Sheridan Rd & Montrose Ave';
update divvy_stations set id = '237' where name = 'Martin Luther King Dr & 29th St';
update divvy_stations set id = '228' where name = 'Damen Ave & Melrose Ave';
update divvy_stations set id = '239' where name = 'Western Ave & Leland Ave';
update divvy_stations set id = '234' where name = 'Clark St & Montrose Ave';
update divvy_stations set id = '236' where name = 'Sedgwick St & Schiller St';
update divvy_stations set id = '223' where name = 'Clifton Ave & Armitage Ave';
update divvy_stations set id = '241' where name = 'Morgan St & Polk St';
update divvy_stations set id = '238' where name = 'Ravenswood Ave & Montrose Ave';
update divvy_stations set id = '243' where name = 'Lincoln Ave & Leavitt St';
update divvy_stations set id = '242' where name = 'Damen Ave & Leland Ave';
update divvy_stations set id = '222' where name = 'Milwaukee Ave & Rockwell St';
update divvy_stations set id = '218' where name = 'Wells St & 19th St';
update divvy_stations set id = '248' where name = 'Woodlawn Ave & 55th St';
update divvy_stations set id = '247' where name = 'Shore Drive & 55th St';
update divvy_stations set id = '193' where name = 'State St & 29th St';
update divvy_stations set id = '245' where name = 'Clarendon Ave & Junior Ter';
update divvy_stations set id = '246' where name = 'Ashland Ave & Belle Plaine Ave';
update divvy_stations set id = '342' where name = 'Wolcott Ave & Polk St';
update divvy_stations set id = '148' where name = 'State St & 33rd St';
update divvy_stations set id = '259' where name = 'California Ave & Francis Pl';
update divvy_stations set id = '261' where name = 'Hermitage Ave & Polk St';
update divvy_stations set id = '113' where name = 'Bissell St & Armitage Ave';
update divvy_stations set id = '256' where name = 'Broadway & Sheridan Rd';
update divvy_stations set id = '253' where name = 'Clifton Ave & Lawrence Ave';
update divvy_stations set id = '132' where name = 'Wentworth Ave & 24th St';
update divvy_stations set id = '338' where name = 'Calumet Ave & 18th St';
update divvy_stations set id = '292' where name = 'Southport Ave & Clark St';
update divvy_stations set id = '254' where name = 'Pine Grove Ave & Irving Park Rd';
update divvy_stations set id = '258' where name = 'Logan Blvd & Elston Ave';
update divvy_stations set id = '257' where name = 'Lincoln Ave & Waveland Ave';
update divvy_stations set id = '277' where name = 'Ashland Ave & Grand Ave';
update divvy_stations set id = '268' where name = 'Lake Shore Dr & North Blvd';
update divvy_stations set id = '271' where name = 'Cottage Grove Ave & 43rd St';
update divvy_stations set id = '275' where name = 'Ashland Ave & 13th St';
update divvy_stations set id = '276' where name = 'California Ave & North Ave';
update divvy_stations set id = '272' where name = 'Indiana Ave & 31st St';
update divvy_stations set id = '274' where name = 'Racine Ave & 15th St';
update divvy_stations set id = '281' where name = 'Western Ave & 24th St';
update divvy_stations set id = '287' where name = 'Franklin St & Arcade Pl';
update divvy_stations set id = '291' where name = 'Wells St & Evergreen Ave';
update divvy_stations set id = '296' where name = 'Broadway & Belmont Ave';
update divvy_stations set id = '282' where name = 'Halsted St & Maxwell St';
update divvy_stations set id = '280' where name = 'Morgan St & 31st St';
update divvy_stations set id = '288' where name = 'Larrabee St & Armitage Ave';
update divvy_stations set id = '278' where name = 'Wallace Ave & 35th St';
update divvy_stations set id = '284' where name = 'Michigan Ave & Jackson Blvd';
update divvy_stations set id = '283' where name = 'LaSalle St & Jackson Blvd';
update divvy_stations set id = '286' where name = 'Franklin St & Quincy St';
update divvy_stations set id = '289' where name = 'Wells St & Concord Ln';
update divvy_stations set id = '260' where name = 'Kedzie Ave & Milwaukee Ave';
update divvy_stations set id = '267' where name = 'Lake Park Ave & 47th St';
update divvy_stations set id = '263' where name = 'Rhodes Ave & 32nd St';
update divvy_stations set id = '265' where name = 'Cottage Grove Ave & Oakwood Blvd';
update divvy_stations set id = '264' where name = 'Stetson Ave & South Water St';
update divvy_stations set id = '293' where name = 'Broadway & Wilson Ave';
update divvy_stations set id = '294' where name = 'Broadway & Berwyn Ave';
update divvy_stations set id = '295' where name = 'Broadway & Argyle St';
update divvy_stations set id = '301' where name = 'Clark St & Schiller St';
update divvy_stations set id = '299' where name = 'Halsted St & Roscoe St';
update divvy_stations set id = '297' where name = 'Paulina St & Montrose Ave';
update divvy_stations set id = '303' where name = 'Broadway & Cornelia Ave';
update divvy_stations set id = '304' where name = 'Halsted St & Waveland Ave';
update divvy_stations set id = '309' where name = 'Leavitt St & Armitage Ave';
update divvy_stations set id = '302' where name = 'Sheffield Ave & Wrightwood Ave';
update divvy_stations set id = '310' where name = 'Damen Ave & Charleston St';
update divvy_stations set id = '315' where name = 'Leavitt St & Hirsch St';
update divvy_stations set id = '317' where name = 'Wood St & Taylor St';
update divvy_stations set id = '318' where name = 'Southport Ave & Irving Park Rd';
update divvy_stations set id = '323' where name = 'Sheridan Rd & Lawrence Ave';
update divvy_stations set id = '131' where name = 'Lincoln Ave & Belmont Ave';
update divvy_stations set id = '325' where name = 'Clark St & Winnemac Ave';
update divvy_stations set id = '306' where name = 'Sheridan Rd & Buena Ave';
update divvy_stations set id = '307' where name = 'Southport Ave & Clybourn Ave';
update divvy_stations set id = '327' where name = 'Sheffield Ave & Webster Ave';
update divvy_stations set id = '316' where name = 'Damen Ave & Sunnyside Ave';
update divvy_stations set id = '329' where name = 'Lake Shore Dr & Diversey Pkwy';
update divvy_stations set id = '308' where name = 'Seeley Ave & Roscoe St';
update divvy_stations set id = '334' where name = 'Lake Shore Dr & Belmont Ave';
update divvy_stations set id = '326' where name = 'Clark St & Leland Ave';
update divvy_stations set id = '333' where name = 'Ashland Ave & Blackhawk St';
update divvy_stations set id = '337' where name = 'Clark St & Chicago Ave';
update divvy_stations set id = '332' where name = 'Halsted St & Diversey Pkwy';
update divvy_stations set id = '331' where name = 'Halsted St & Blackhawk St';
update divvy_stations set id = '339' where name = 'Emerald Ave & 31st St';
update divvy_stations set id = '298' where name = 'Lincoln Ave & Belle Plaine Ave';
update divvy_stations set id = '324' where name = 'Stockton Dr & Wrightwood Ave';
update divvy_stations set id = '345' where name = 'Lake Park Ave & 56th St';
update divvy_stations set id = '344' where name = 'Wolcott Ave & Lawrence Ave';
update divvy_stations set id = '290' where name = 'Kedzie Ave & Palmer Ct';
update divvy_stations set id = '346' where name = 'Ada St & Washington Blvd';
update divvy_stations set id = '336' where name = 'Cottage Grove Ave & 47th St';
update divvy_stations set id = '335' where name = 'Calumet Ave & 35th St';
update divvy_stations set id = '343' where name = 'Racine Ave & Wrightwood Ave';